name: custom-image
namespace: default
runtime: python39
runtimeImageOverride: kwiatekus/python-runtime-debian
source:
    sourceType: inline
    sourcePath: /Users/krzysztofkwiatosz/go/src/github.com/kwiatekus/kyma-serverless-runtime-override/src/custom-runtime
env:
    - name: foo
      value: bar
apiRules:
    - service:
        host: custom-image.kk.wookiee.shoot.canary.k8s-hana.ondemand.com
      rules:
        - methods:
            - GET
          accessStrategies:
            - handler: allow
