name: custom-image
namespace: default
runtime: python39
runtimeImageOverride: kwiatekus/python-runtime-debian
source:
    sourceType: git
    url: https://github.com/kwiatekus/kyma-serverless-runtime-override.git
    repository: kyma-serverless-runtime-override
    reference: main
    baseDir: /src/custom-runtime/
env:
    - name: foo
      value: bar
apiRules:
    - service:
        host: custom-image.kk.wookiee.shoot.canary.k8s-hana.ondemand.com
      rules:
        - methods:
            - GET
          accessStrategies:
            - handler: allow
